const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('mailpilot', {
  isLocalSourceBuild: process.defaultApp === true,
  // Opt-in local demo mode. It is intentionally unavailable in packaged builds.
  isDemoMode: process.env.MAILBOAT_DEMO_MODE === '1' && process.defaultApp === true,
  selectFile: () => ipcRenderer.invoke('select-file'),
  downloadImportSample: () => ipcRenderer.invoke('download-import-sample'),
  selectAttachments: () => ipcRenderer.invoke('select-attachments'),
  saveDroppedFile: (name, base64) => ipcRenderer.invoke('save-dropped-file', name, base64),
  getDashboardData: (payload) => ipcRenderer.invoke('get-dashboard', payload),
  importExcel: (filePath, account, baseTime) => ipcRenderer.invoke('import-excel', filePath, account, baseTime),
  importPaste: (text, account, baseTime) => ipcRenderer.invoke('import-paste', text, account, baseTime),
  saveAccounts: (payload) => ipcRenderer.invoke('save-accounts', payload),
  listMailTemplates: () => ipcRenderer.invoke('list-mail-templates'),
  saveMailTemplate: (payload) => ipcRenderer.invoke('save-mail-template', payload),
  deleteMailTemplate: (name) => ipcRenderer.invoke('delete-mail-template', name),
  startSend: (account, userId) => ipcRenderer.invoke('start-send', { account, userId }),
  stopSend: (account) => ipcRenderer.invoke('stop-send', account),
  testSend: (text, account, startTime, userId) => ipcRenderer.invoke('test-send', { text, account, startTime, userId }),
  stopTestSend: () => ipcRenderer.invoke('stop-test-send'),
  testSmtp: (account) => ipcRenderer.invoke('test-smtp', account),
  gmailOauthBind: (email) => ipcRenderer.invoke('gmail-oauth-bind', email),
  gmailOauthUnbind: (email) => ipcRenderer.invoke('gmail-oauth-unbind', email),
  gmailOauthStatus: (email) => ipcRenderer.invoke('gmail-oauth-status', email),
  setGmailCredentials: () => ipcRenderer.invoke('set-gmail-credentials'),
  getGmailCredentialsStatus: () => ipcRenderer.invoke('get-gmail-credentials-status'),
  // Legacy aliases kept for existing renderer code paths.
  setGmailClientSecret: () => ipcRenderer.invoke('set-gmail-client-secret'),
  getGmailClientSecretStatus: () => ipcRenderer.invoke('get-gmail-client-secret-status'),
  exportReport: () => ipcRenderer.invoke('export-report'),
  sendFeedback: (payload) => ipcRenderer.invoke('send-feedback', payload),
  getAnnouncement: (payload) => ipcRenderer.invoke('get-announcement', payload),
  listAnnouncements: () => ipcRenderer.invoke('list-announcements'),
  getStorageInfo: () => ipcRenderer.invoke('get-storage-info'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  openExternalUrl: (url) => ipcRenderer.invoke('open-external-url', url),
  selectStorageDir: () => ipcRenderer.invoke('select-storage-dir'),
  windowMinimize: () => ipcRenderer.invoke('window-minimize'),
  windowMaximize: () => ipcRenderer.invoke('window-maximize'),
  windowClose: () => ipcRenderer.invoke('window-close'),
  deleteTeachers: (emails) => ipcRenderer.invoke('delete-teachers', emails),
  toggleAlwaysOnTop: () => ipcRenderer.invoke('toggle-always-on-top'),
});
